/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   Do not edit this file directly. Any changes will be lost.           ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

import type Opa5 from "sap/ui/test/Opa5";
import type { actions as ListReportActions, assertions as ListReportAssertions } from "sap/fe/test/ListReport";
import type { actions as ObjectPageActions, assertions as ObjectPageAssertions } from "sap/fe/test/ObjectPage";
import type { actions as TemplatePageActions, assertions as TemplatePageAssertions } from "sap/fe/test/TemplatePage";
import type Shell from "sap/fe/test/Shell";
import type BaseArrangements from "sap/fe/test/BaseArrangements";
import type { actions as OrdersListGeneratedCustomActions, assertions as OrdersListGeneratedCustomAssertions } from "../pages/OrdersList.gen";
import type { actions as OrdersObjectPageGeneratedCustomActions, assertions as OrdersObjectPageGeneratedCustomAssertions } from "../pages/OrdersObjectPage.gen";
import type { actions as OrderDetailsObjectPageGeneratedCustomActions, assertions as OrderDetailsObjectPageGeneratedCustomAssertions } from "../pages/OrderDetailsObjectPage.gen";

export type Given = Opa5 & BaseArrangements & {
    iTearDownMyApp: () => Given;
    iStartMyApp: (sAppHash?: string, mInUrlParameters?: object) => Given;
    and: Given;
};

export type When = Opa5 & BaseArrangements & {
    onTheOrdersListGenerated: Opa5 & ListReportActions & TemplatePageActions & typeof OrdersListGeneratedCustomActions;
    onTheOrdersObjectPageGenerated: Opa5 & ObjectPageActions & TemplatePageActions & typeof OrdersObjectPageGeneratedCustomActions;
    onTheOrderDetailsObjectPageGenerated: Opa5 & ObjectPageActions & TemplatePageActions & typeof OrderDetailsObjectPageGeneratedCustomActions;
    onTheShell: Shell;
};

export type Then = Opa5 & BaseArrangements & {
    onTheOrdersListGenerated: Opa5 & ListReportAssertions & TemplatePageAssertions & typeof OrdersListGeneratedCustomAssertions;
    onTheOrdersObjectPageGenerated: Opa5 & ObjectPageAssertions & TemplatePageAssertions & typeof OrdersObjectPageGeneratedCustomAssertions;
    onTheOrderDetailsObjectPageGenerated: Opa5 & ObjectPageAssertions & TemplatePageAssertions & typeof OrderDetailsObjectPageGeneratedCustomAssertions;
    onTheShell: Shell;
};
